Dot2 is method(ax as float, ay as float, bx as float, by as float) as float {
  return ax * bx + ay * by;
}

Dot3 is method(ax as float, ay as float, az as float, bx as float, by as float, bz as float) as float {
  return ax * bx + ay * by + az * bz;
}

Dot4 is method(ax as float, ay as float, az as float, aw as float, bx as float, by as float, bz as float, bw as float) as float {
  return ax * bx + ay * by + az * bz + aw * bw;
}

