Sin is method(angle as float) as float {
  return angle;
}

Cos is method(angle as float) as float {
  return angle;
}

Tan is method(angle as float) as float {
  return angle;
}

Asin is method(value as float) as float {
  return value;
}

Acos is method(value as float) as float {
  return value;
}

Atan is method(value as float) as float {
  return value;
}

Atan2 is method(y as float, x as float) as float {
  return y;
}

